### ISSUE TITLE
[MELHORIA]CRUD Forwardings (Áreas/Secretarias)

### ISSUE THREAD

**Issue by lucasferreiraunicef** [UNICEF01/BAV#174]
Atividades relacionadas:

Área/secretaria 
     - Ao acessar a tela, verificar se já existe as opções de Secretaria Municipal de Educação e Secretaria Municipal de Assistência Social (secreatarias defaults) por municipio. -> Uma vez que o município realiza a adesão, as áreas referenciadas acima devem estar criadas.

[Link](https://xd.adobe.com/view/343271d4-6e28-4037-b01e-e3a977449d3b-6161/screen/fcd86db0-6ed1-4cf5-9485-c3950ef95bde)

**Comment by dlazaroni** [comment]
@lukasfigueiredo Alterar secretaria "Saúde" para "Assistência social"
