### ISSUE TITLE
Vacinas

### ISSUE THREAD

**Issue by lucasferreiraunicef** [UNICEF01/BAV#178]
- botão editar errado.
        - adicionar todas as vacinas (planilha) : https://unicef-my.sharepoint.com/:x:/g/personal/dlazaroni_unicef_org/Ec98qn8nQJFCidpNfHBWKhQBx2BU6eC7S9QZtNjxmbmebQ?e=eHQUpW
        - remover botões de ações. (adicionar cadeado)
        - listar campo "intervalo ideal" na tela
        - trazer o campo dose para ao lado do campo vacina

[Protótipo](https://xd.adobe.com/view/343271d4-6e28-4037-b01e-e3a977449d3b-6161/screen/37dfb2b0-bb85-46db-b437-f67b4fd55e31 )

**Comment by dlazaroni** [comment]
![image.png](https://images.zenhubusercontent.com/6232777dbf0d5a6437a41ee5/f918df7d-d0ff-461c-a73b-2b30cc47a903)
