### ISSUE TITLE
Prazo (Etapas)

### ISSUE THREAD

**Issue by lucasferreiraunicef** [UNICEF01/BAV#180]
**Regra de negócio:**

- limite de prazo para no MÁXIMO 30 dias. (regra) - (Configurável via admin)

Etapas:

- Análise Técnica
- Encaminhamento
- Sala de vacina

**Comment by dlazaroni** [comment]
![image.png](https://images.zenhubusercontent.com/6232777dbf0d5a6437a41ee5/08f61bb7-fbbb-4721-9f70-9cf7e58ff702)
