### ISSUE TITLE
[Caso] Análise Técnica

### ISSUE THREAD

**Issue by dlazaroni** [UNICEF01/BAV#235]
**Descrição:** Nesta etapa, é analisada os alertas emitidos com o estado vacinal "**vacinação em atraso**" durante a emissão do alerta. Aqui, o GESTOR MUNICIPAL, TÉCNICO VERIFICADOR, COORDENADOR OPERACIONAL e SUPERVISOR DE SAÚDE consegue iniciar a análise para:
1) Visualizar ou editar os dados do alerta:
![image.png](https://images.zenhubusercontent.com/6232777dbf0d5a6437a41ee5/704ae1fc-f01e-409e-b599-617c53129866)
*Obs: aqui pode deixar os campos abertos para edição e adicionar um botão "SALVAR" no final do componente.
2) Componente de visualização das fotos da carteirinha de vacinação. Slider + ZOOM;
3) Confirmar ou alterar os motivos - Remover botão "Confirmar"
4) Ao clicar no botão "Iniciar Análise Técnica" o usuário é atribuído para esse alerta (sem botão "alterar"):
![image.png](https://images.zenhubusercontent.com/6232777dbf0d5a6437a41ee5/23e95d88-feda-4607-b9f6-08c984b6b5dd)
5) E efetuar a situação desse alerta: VACINAÇÃO EM DIA ou VACINAÇÃO EM ATRASO:
![image.png](https://images.zenhubusercontent.com/6232777dbf0d5a6437a41ee5/dd569195-8622-4821-9cf9-af088ca9eb97)

**Regras:**
1) Ao definir a análise como "VACINAÇÃO EM DIA", deverá ser direcionado para uma tela de sucesso:
Link: https://xd.adobe.com/view/5a76f741-3583-4d50-8ac6-23c88cffc720-0f25/screen/d8e2544b-6e79-4a55-9173-b14fb34bc13d
» Deixar uma tela simples. Alterar "caso concluído" para "alerta rejeitado"
2) Ao definir a análise como "VACINAÇÃO EM ATRASO", a análise técnica é concluída e o alerta vira um caso na etapa ENCAMINHAMENTO.

**Link para AGENTE DE ALERTA, SUPERVISOR ASSISTÊNCIA SOCIAL, SUPERVISOR EDUCAÇÃO:** https://xd.adobe.com/view/5a76f741-3583-4d50-8ac6-23c88cffc720-0f25/screen/29d01fce-dc80-4f92-ad71-48fc46622b33 

**Link para GESTOR MUNICIPAL, TÉCNICO VERIFICADOR, COORDENADOR OPERACIONAL, SUPERVISOR DE SAÚDE:** https://xd.adobe.com/view/5a76f741-3583-4d50-8ac6-23c88cffc720-0f25/screen/26180220-7d3c-4de5-aa31-bb3bfed9788f 

**Não entra:**
» Atribuir usuário:
![image.png](https://images.zenhubusercontent.com/6232777dbf0d5a6437a41ee5/6b001eb4-eb99-4287-962c-d14a7c2a62d2)
» Designar téc. verificador:
![image.png](https://images.zenhubusercontent.com/6232777dbf0d5a6437a41ee5/c42cc8d1-e26f-4f50-9b0b-6f94ea322690)
» Encaminhar / Encerrar:
![image.png](https://images.zenhubusercontent.com/6232777dbf0d5a6437a41ee5/8f6e93d0-27f4-49b0-99c9-2718b3c46366)
» Adicionar nova Anotação:
![image.png](https://images.zenhubusercontent.com/6232777dbf0d5a6437a41ee5/a4158866-5fe0-4851-b044-a14e93a05db5)
» Datas para as Vacinas com doses em andamento: 
![image.png](https://images.zenhubusercontent.com/6232777dbf0d5a6437a41ee5/02137de0-997b-4d66-99c0-eea5816a9c58)

**Comment by lucasferreiraunicef** [comment]
Critérios de aceite:

 

- [x] Conter a jornada de usuário completa.

 

- [x] Todas as validações de campo devem estar funcionando.

 

- [x] Deve Conter todos os componentes de tela desenvolvidos com base no protótipo da sprint atual.

 

- [x] Deve ser aceito e aprovado em homologação.
