### ISSUE TITLE
[Caso] Encaminhamento

### ISSUE THREAD

**Issue by dlazaroni** [UNICEF01/BAV#236]
**Descrição:** Etapa de Encaminhamento onde é realizado o "encaminhamento" do paciente para a "Sala de Vacina".

**Regra:**

É enviado para a etapa de encaminhamento os alertas emitidos com os status relacionados abaixo:

- Sem carteirinha

- Não vacinado

- Atraso vacinal (Após conclusão da análise técnica, com **atraso vacinal**)

**Não entra:**

1)
![Captura de Tela 2023-03-31 às 09.19.25.png](https://images.zenhubusercontent.com/6239dbfdd8cc266a1b2acd2e/6f5e8b14-2d61-4272-9571-0c2960b11e26)

2)
![Captura de Tela 2023-03-31 às 09.24.33.png](https://images.zenhubusercontent.com/6239dbfdd8cc266a1b2acd2e/973c636e-0da9-48c7-b44f-163ddfc71b9a)

**OBSERVACÃO:**  

1 ) Manter o STATUS vacinal mesmo se tratando de doses dependentes.

![Captura de Tela 2023-03-31 às 10.27.39.png](https://images.zenhubusercontent.com/6239dbfdd8cc266a1b2acd2e/6ee7d418-a7d7-4510-af97-657ffd7bcdba)

2 ) O Botão de "SALA DE VACINA" deverá encaminhar para a seguinte page abaixo:

Botão
![Captura de Tela 2023-03-31 às 09.26.01.png](https://images.zenhubusercontent.com/6239dbfdd8cc266a1b2acd2e/6c96c534-8bb6-49d3-b64c-acfdbc99416f)

Page
![MicrosoftTeams-image (7).png](https://images.zenhubusercontent.com/6239dbfdd8cc266a1b2acd2e/a801ab0e-be6e-45ca-8eee-d720b34d0bc9)

**[A PARTIR DA PÁGINA 38]**
**Link:** https://xd.adobe.com/view/5a76f741-3583-4d50-8ac6-23c88cffc720-0f25/screen/49f74a05-1c4f-440e-8db7-de40554fceca

**Ícones:** [https://app.zenhub.com/files/470780401/d45a716f-49de-4072-bea0-c74a7e3133fa/download](https://app.zenhub.com/files/470780401/d45a716f-49de-4072-bea0-c74a7e3133fa/download)

**Comment by lucasferreiraunicef** [comment]
Critérios de aceite:

 

- [x] Conter a jornada de usuário completa.

 

- [x] Todas as validações de campo devem estar funcionando.

 

- [x] Deve Conter todos os componentes de tela desenvolvidos com base no protótipo da sprint atual.

 

- [x] Deve ser aceito e aprovado em homologação.
