### ISSUE TITLE
[Caso] Sala de vacina

### ISSUE THREAD

**Issue by dlazaroni** [UNICEF01/BAV#237]
**Descrição:** Etapa na qual o **Técnico verificador ou Agente de saúde**, realiza as aplicações das vacinas que estão classificadas como **"ATRASO VACINAL"**.

**Regra:**

**1 -** Deverá aparecer em tela os seguintes dados abaixo:

![Captura de Tela 2023-04-17 às 14.14.19.png](https://images.zenhubusercontent.com/6239dbfdd8cc266a1b2acd2e/daf32feb-e6fb-428c-8190-c06cb964c58c)
![Captura de Tela 2023-04-17 às 14.14.50.png](https://images.zenhubusercontent.com/6239dbfdd8cc266a1b2acd2e/71b43f10-4d89-4b64-8f7b-d0d7e9485b06)

**2 -** Ao selecionar a vacina a ser aplicada, a data deve ser inserida para efetuar o registro.

![Captura de Tela 2023-04-17 às 14.21.14.png](https://images.zenhubusercontent.com/6239dbfdd8cc266a1b2acd2e/bcbfdd4a-4a29-4a0d-9cfb-c9e323073214)

**3 -** Após a conclusão da vacinação, devemos redirecionar o usuário para a tela com os seguintes componentes:

![Captura de Tela 2023-04-17 às 14.24.16.png](https://images.zenhubusercontent.com/6239dbfdd8cc266a1b2acd2e/f297dadd-3606-417a-9f6d-515f96b036ee)

Se tentar finalizar com 1 ou mais vacinas em atraso, será necessário inserir o motivo:

![Captura de Tela 2023-04-17 às 14.29.00.png](https://images.zenhubusercontent.com/6239dbfdd8cc266a1b2acd2e/0639f56a-e70f-4b0c-ab40-54a161389295)

**4 -** Uma vez que a etapa esteja como "CONCLUÍDA", será possível efetuar o "ENCAMINHAMENTO" ou registrar uma nova "VISITA"

![Captura de Tela 2023-04-17 às 14.32.59.png](https://images.zenhubusercontent.com/6239dbfdd8cc266a1b2acd2e/d85fe81c-9a38-48c4-8c19-a0a810a67e80)

**Protótipo:**

[UI - Protótipo](https://xd.adobe.com/view/5a76f741-3583-4d50-8ac6-23c88cffc720-0f25/screen/6fa202b3-4649-435f-8632-cb8e700cdcbe/)
Telas de 44 a 52

**Fluxograma:**

![Captura de Tela 2023-04-17 às 14.39.03.png](https://images.zenhubusercontent.com/6239dbfdd8cc266a1b2acd2e/446a5cca-3b95-4482-b441-4602e8c9e88a)

**Comment by lucasferreiraunicef** [comment]
Critérios de aceite:

 

- [x] Conter a jornada de usuário completa.

 

- [x] Todas as validações de campo devem estar funcionando.

 

- [x] Deve Conter todos os componentes de tela desenvolvidos com base no protótipo da sprint atual.

 

- [x] Deve ser aceito e aprovado em homologação.
