### ISSUE TITLE
[Lembrete] E-mail

### ISSUE THREAD

**Issue by dlazaroni** [UNICEF01/BAV#240]
Description: O e-mail deverá ser enviado em dois momentos extremamente importantes:

**1 ) E-mail - Disparar imediatamente após a etapa de "Análise técnica" (constatado o ATRASO VACINAL) dizendo que o USUÁRIO possui X dias para tomar as vacinas.**

*X dias = prazo determinado pelo município para a etapa de encaminhamento

**Atenção: Enviar email para mãe e/ou para o pai.**

a) Texto E-mail:
   a.1) Assunto: Seu filho(a) está com vacinas em atraso!
   a.2) Texto: Olá _mãe/responsável_ / _pai/responsável_ do(a) [_Nome_da_Crianca_], a **Busca Ativa Vacinal** do município [_Nome_do_Municipio_] veio te lembrar que seu(ua) filho(a) está com as seguintes vacinas em atrasos:

- [Vacina 1 / Dose X]
- [Vacina 2 / Dose Y]
- [Vacina 3]

   Dirija-se até a sala de vacina da [_Nome_da_UBS_] no prazo de até [X] dias:

   Local: [_Endereco_UBS_]

   Não se esqueça de levar a carteirinha de vacinação.

   Esperamos você lá!

   _Caso você já tenha aplicado essas vacinas, desconsidere esta mensagem._

   Vacinas Progetem. Vacinas salvam vidas!

**2 ) E-mail - Disparar 7 dias antes do vencimento do prazo do "Encaminhamento"** - Email enviado apenas se o caso não estiver concluído.

a) Texto E-mail:
   a.1) Assunto: Seu filho(a) está com vacinas em atraso!
   a.2) Texto: Olá mãe/responsável pai/responsável do(a) [_Nome_da_Crianca_], a **Busca Ativa Vacinal** do município [_Nome_do_Municipio_] veio te lembrar que seu(ua) filho(a) está com as seguintes vacinas em atrasos:
   
- [Vacina 1 / Dose X]
- [Vacina 2 / Dose Y]
- [Vacina 3]

   Dirija-se até a sala de vacina da [_Nome_da_UBS_] no prazo de até 7 dias:

   Local: [_Endereco_UBS_]

   Não se esqueça de levar a carteirinha de vacinação.

   Esperamos você lá!

   _Caso você já tenha aplicado essas vacinas, desconsidere esta mensagem._

   Vacinas Progetem. Vacinas salvam vidas!

**Comment by lucasferreiraunicef** [comment]
Critérios de aceite:

 

- [x] Conter a jornada de usuário completa.

 

- [x] Todas as validações de campo devem estar funcionando.

 

- [x] Deve Conter todos os componentes de tela desenvolvidos com base no protótipo da sprint atual.

 

- [x] Deve ser aceito e aprovado em homologação.
