### ISSUE TITLE
[Casos] Listagem

### ISSUE THREAD

**Issue by dlazaroni** [UNICEF01/BAV#242]
Para todas as visualizações que estão atreladas aos perfis de utilização do sistema BAV, devemos seguir a orientação abaixo: 

![image.png](https://images.zenhubusercontent.com/6232777dbf0d5a6437a41ee5/96589e68-bbf2-443a-9628-4fdd58632af3)

**Comment by lucasferreiraunicef** [comment]
Critérios de aceite:

 

- [x] Conter a jornada de usuário completa.

 

- [x] Todas as validações de campo devem estar funcionando.

 

- [x] Deve Conter todos os componentes de tela desenvolvidos com base no protótipo da sprint atual.

 

- [x] Deve ser aceito e aprovado em homologação.
