### ISSUE TITLE
Bug CPF iniciado com ZERO

### ISSUE THREAD

**Issue by dlazaroni** [UNICEF01/BAV#249]
Há um bug na adesão que quando o CPF do prefeito inicia com o número ZERO (0), o sistema não aprova automaticamente a adesão mesmo que o CPF esteja correto na base de dados do TSE.

1) Corrigir o erro do sistema desconsiderar o ZERO no início do CPF;
2) Rodar script para aprovar automaticamente a lista de municípios pendentes - https://unicef-my.sharepoint.com/:x:/g/personal/dlazaroni_unicef_org/EW4MUpziSPhLpHjlE9-SPucBviCF81q9vs16mdbelur38g?e=3ipy4E - desde que o CPF dos prefeitos desta lista estejam de acordo com o CPF no TSE;
3) Se certificar que ao ser aprovado automaticamente, o gestor receba o email.
4) Passar status de quais desses municípios não foram aprovados automaticamente

**Comment by lukasfigueiredo** [comment]
1 - Identifiquei que o arquivo do TSE está com alguns CPFs "errado" faltando o(s) primeiro(s) caracter quando é "0"
2 - Ao rodar o script devo assumir que os CPF que tiverem 10 caracteres e o primeiro caracter não seja "0", dessa forma vai encontrar o mesmo número no arquivo do TSE
3 - o script vai seguir o fluxo normal de uma aprovação automatica
4 - Se refere aos municípios após rodar o script ou antes de rodar o script?
