### ISSUE TITLE
Ajustes finos de Configurações

### ISSUE THREAD

**Issue by dlazaroni** [UNICEF01/BAV#250]
- [x] Importar apenas as salas de vacina da planilha ESTABELECIMENTOS que pertencem ao TP_TIPO_ESTABELECIMENTO igual a 1 (Unidade Básica de Saúde - UBS);
- [x] Bug na criação / edição de regional e sub-regional
- [x] Alterar nome de GRUPOS para REGIÕES
- [x] Alterar "Regional" e "Regional padrão" para "Região";
- [x] Alterar "Sub Regional" e "Sub Regional padrão" para "Sub Região";
- [x] Verificar o motivo de alguns perfis (coordenador@bav.org.br / senha: 123!bavbav) não terem visualizado os botões de editar em Motivos e Áreas/Secretarias;
- [x] A listagem de vacinas sumiu. Além disso, corrigir o número de "Intervalo ideal entre-doses" da primeira dose da vacina "Poliomielite (VIP)". Atualmente está 60 dias e deve ser 0.

**Comment by dlazaroni** [comment]
**Testes usando o perfil coordenador@bav.org.br / senha: 123!bavbav**

Bug na criação de sub-regional permanece:
![image.png](https://images.zenhubusercontent.com/6232777dbf0d5a6437a41ee5/66f307f6-ffd5-45e9-8c90-e96d817cafe5)

- [x] Novo bug: ao acessar com o perfil de coordenador de um município, estou conseguindo visualizar todas as regionais e todas as sub-regionais de todos os municípios. A opção de seleção de estado/município deve vir pré-preenchida de acordo com o município do usuário e bloqueada (o usuário não consegue alterar). Esse comportamento já estava funcionando anteriormente. Depois vi que isso aconteceu, muito provavelmente após um logout como gestor nacional e depois login como coordenador desse município.

- [x] BUG: Ao criar uma nova regional, a sub-regional padrão dela estava com as mesmas salas de vacina da sub-regional padrão da regional padrão que o município. Esse comportamento não acontecia antes também.

- [x] Alterar os títulos abaixo de "Regionais" para "Regiões" e "Sub-regionais" para "Sub Regiões":
![image.png](https://images.zenhubusercontent.com/6232777dbf0d5a6437a41ee5/aa73eb61-6bc4-406b-9be8-6ee7464b8f7d)

- [x] Ao selecionar uma sala de vacina para mover, as opções de regionais (regiões) aparecem de todos os municípios:
![image.png](https://images.zenhubusercontent.com/6232777dbf0d5a6437a41ee5/370b7fe5-0f1b-4f1c-b7b0-2ceb91a0a4a2)

- [x] No print acima, alterar onde tem "Regional" para "Região";

- [x] No print acima, tentar deixar o nome completo da Sala de vacina;

**Comment by dlazaroni** [comment]
@rodrigoluzlopes conseguiu finalizar esses ajustes?

**Comment by rodrigoluzlopes** [comment]
Bom dia. Poderia testar, por gentileza?

**Comment by dlazaroni** [comment]
@rodrigoluzlopes homologado... Tudo ok por aqui...
