### ISSUE TITLE
Login - Novo Usuário - Frontend

### ISSUE THREAD

**Issue by Clivisonc** [UNICEF01/BAV#27]

**Comment by leonardodms-unicef** [comment]
![BAV.bg.Login.V3.1.svg](https://images.zenhubusercontent.com/6238d800e86dbd04066d7833/7f030791-dea3-4f2c-8de5-83f97a500f80)

(https://images.zenhubusercontent.com/6238d800e86dbd04066d7833/6f19ba35-90e9-4229-a69a-bc88178f1dfa)

**Comment by leonardodms-unicef** [comment]
![BAV.logo.principal.svg](https://images.zenhubusercontent.com/6238d800e86dbd04066d7833/cf224aee-ff11-4a6e-bef0-d2145608482b)

(https://images.zenhubusercontent.com/6238d800e86dbd04066d7833/76098bf2-0a27-4089-9af9-f93d3da78751)

**Comment by rodrigoluzlopes** [comment]
@leonardodms-unicef , os cantos da imagem background são brancos mesmo? É um espaço considerável, está correto?

**Comment by leonardodms-unicef** [comment]
No SVG? Não. Só vale a área cinza. Deixa eu gerar um novo arquivo

**Comment by rodrigoluzlopes** [comment]
Exatamente. Muito obrigado
