### ISSUE TITLE
Consulta banco para Abaetetuba

### ISSUE THREAD

**Issue by dlazaroni** [UNICEF01/BAV#302]
1- ID município: afc2772b-3d1b-4e60-b671-a0b6dd5cbd4f (quero ver qual o status no banco e quais pendências)

2- ID prefeito: 90884411-8b31-4de8-872b-000bfaf9b3a3 (quero saber se ele aceitou os termos e cadastrou uma senha)

3- ID gestor: 777640a9-e161-406b-9330-7492f0d20bea (quero saber se ele criou sua senha para acessar a plataforma)

**Comment by rodrigoluzlopes** [comment]
Evidências. 

Accession / adesão
![image.png](https://images.zenhubusercontent.com/6239f54b63de657fb9b4082c/e444b564-3383-4e9b-8332-6030f100118b)


![image.png](https://images.zenhubusercontent.com/6239f54b63de657fb9b4082c/1939fe7c-698d-4aea-8ce1-c129699cc482)


Conforme vista na imagem, o gestor político (Francineti Maria Rodrigues Carvalho) não cadastrou sua senha ainda.

**Comment by rodrigoluzlopes** [comment]
Errata: Francineti Maria é, na verdade, a prefeita e cadastrou a senha.
