### ISSUE TITLE
Exclusão de município sem usuário prefeito ou gestor (usuários apagados)

### ISSUE THREAD

**Issue by dlazaroni** [UNICEF01/BAV#315]
![image.png](https://images.zenhubusercontent.com/6232777dbf0d5a6437a41ee5/5f381686-50da-489f-95a7-08e198b2c25b)

https://buscaativavacinal.org.br/accession/manage/8daa4630-a897-4092-bb43-d7f9513dea05#

https://buscaativavacinal.org.br/accession/manage/cd724cca-662b-42dc-9518-558de6e766db#

https://buscaativavacinal.org.br/accession/manage/8cf71a18-1fdd-4f8e-989a-054605dda563

Não consigo excluir os municípios acima porque usuários da adesão (prefeito e/ou gestor político) foram excluídos.

**Portanto:**

**1) Nenhum usuário pode excluir usuários com perfil de "gestor da política municipal" ou "prefeito"**
**2) O gestor nacional deve conseguir excluir uma adesão que está com usuário prefeito ou gestor excluído/vazios.**

Critérios de Aceite:

- [x] Homologação de negócio
- [x] Componentes equivalentes ao Protótipo

**Comment by lucasferreiraunicef** [comment]
Município teste: 

- Acrelandia -> dlazaroni+12@unicef.org
- Lauro de Freitas -> _lukas.figueiredo@hotmail.com

**Comment by dlazaroni** [comment]
@lucasferreiraunicef @lukasfigueiredo @rodrigoluzlopes validado
