### ISSUE TITLE
Relatorio todas adesoes

### ISSUE THREAD

**Issue by rodrigoluzlopes** [UNICEF01/BAV#317]
Segue relatorio de todas as adesoes da BAV

**Comment by rodrigoluzlopes** [comment]
[https://app.zenhub.com/files/470780401/90da82db-46ee-4f4a-8fa8-ca92527abbd5/download](https://app.zenhub.com/files/470780401/90da82db-46ee-4f4a-8fa8-ca92527abbd5/download)

**Comment by lucasferreiraunicef** [comment]
@rodrigoluzlopes , acabamos por não especificar os PERFIS necessários que devem estar presentes na planilha:

Gestor(a) da Política Pública 
Coordenador(a) Operacional Municipal
Gestor(a) da Política Pública da BAV
Coordenador(a) Operacional Municipal
Supervisores Institucionais da educação, saúde, assistência social, técnicos(as) verificadores e agentes de alertas.

**Comment by rodrigoluzlopes** [comment]
[https://app.zenhub.com/files/470780401/5ede95e1-7edd-4b59-805b-a9f0cda16603/download](https://app.zenhub.com/files/470780401/5ede95e1-7edd-4b59-805b-a9f0cda16603/download)

**Comment by rodrigoluzlopes** [comment]
Conforme solicitado, foram adicionados as colunas de e-mails separadas.

[https://app.zenhub.com/files/470780401/7903a66d-d3e9-48b5-9e88-a8ccb572f31b/download](https://app.zenhub.com/files/470780401/7903a66d-d3e9-48b5-9e88-a8ccb572f31b/download)
