### ISSUE TITLE
Back - Regra aplicacao doses dependentes

### ISSUE THREAD

**Issue by lukasfigueiredo** [UNICEF01/BAV#412]
na sala de vacinas se tiver 2 doeses da vacina e a segunda dependente da primeira e em "atraso"
ao aplicar a primeira dose o caso não é concluído é gerado uma nova etapa de  encaminhamento
o prazo desta nova etapa de encaminhamento só começa a contar a partir passado o intervalo entre as doses tomando como referência a que tiver menor prazo(várias vacinas em atraso pendente)

**Comment by lucasferreiraunicef** [comment]
Critérios de aceite:

 

- [x] Conter a jornada de usuário completa.

 

- [x] Todas as validações de campo devem estar funcionando.

 

- [x] Deve Conter todos os componentes de tela desenvolvidos com base no protótipo da sprint atual.

 

- [x] Deve ser aceito e aprovado em homologação.
