### ISSUE TITLE
Back - Cadastro Alerta Regra vacinas de acordo estado vacinal

### ISSUE THREAD

**Issue by lukasfigueiredo** [UNICEF01/BAV#418]
caso estado vacinal seja "não vacinada" ou "sem carteirinha" marca como não aplicada todas as vacinas de acordo com o público-alvo como não aplicadas e move direto para etapa de encaminhamento

**Comment by lucasferreiraunicef** [comment]
Critérios de aceite:

 

- [x] Conter a jornada de usuário completa.

 

- [x] Todas as validações de campo devem estar funcionando.

 

- [x] Deve Conter todos os componentes de tela desenvolvidos com base no protótipo da sprint atual.

 

- [x] Deve ser aceito e aprovado em homologação.
