### ISSUE TITLE
[Alerta] "Será enviado também para a Secretaria de Educação" - texto aparece quando seleciona o select "criança fora da escola"

### ISSUE THREAD

**Issue by lucasferreiraunicef** [UNICEF01/BAV#421]

**Comment by lukasfigueiredo** [comment]
Ao clicar em uma das opções do grupo "BAE" no formulário de Alerta/Visita só exibir o texto quando seleciona "Criança fora da escola"

**Comment by lucasferreiraunicef** [comment]
Critérios de aceite:

 

- [x] Conter a jornada de usuário completa.

 

- [x] Todas as validações de campo devem estar funcionando.

 

- [x] Deve Conter todos os componentes de tela desenvolvidos com base no protótipo da sprint atual.

 

- [x] Deve ser aceito e aprovado em homologação.
