### ISSUE TITLE
[Alerta] Upload Carteirinha

### ISSUE THREAD

**Issue by lucasferreiraunicef** [UNICEF01/BAV#422]
Description: Perdeu upload da foto da carteirinha mudando o estado vacinal

**Comment by lukasfigueiredo** [comment]
Bug, no upload da carteirinha de vacinação, identificar motivo da incossitência no funcinamento do botão

**Comment by lucasferreiraunicef** [comment]
Critérios de aceite:

 

- [x] Conter a jornada de usuário completa.

 

- [x] Todas as validações de campo devem estar funcionando.

 

- [x] Deve Conter todos os componentes de tela desenvolvidos com base no protótipo da sprint atual.

 

- [x] Deve ser aceito e aprovado em homologação.
