### ISSUE TITLE
[Alerta] RG não pode ser obrigatório

### ISSUE THREAD

**Issue by lucasferreiraunicef** [UNICEF01/BAV#423]

**Comment by lukasfigueiredo** [comment]
Alterar validação FRONT e BACK para campo RG não ser mais obrigatório

**Comment by lucasferreiraunicef** [comment]
Critérios de aceite:

 

- [x] Conter a jornada de usuário completa.

 

- [x] Todas as validações de campo devem estar funcionando.

 

- [x] Deve Conter todos os componentes de tela desenvolvidos com base no protótipo da sprint atual.

 

- [x] Deve ser aceito e aprovado em homologação.
