### ISSUE TITLE
[Configurações] Alerta sem prazo (Corrigir)

### ISSUE THREAD

**Issue by lucasferreiraunicef** [UNICEF01/BAV#428]
Description: A regra não está sendo respeitada durante o fluxo.

Ex: Configurado 15 dias para analise técnica, ao iniciar a analise técnica de um "Alerta" a configuração setada não respeita o prazo definido.

**Comment by lukasfigueiredo** [comment]
Adicionar configuração de prazo para alerta

**Comment by lucasferreiraunicef** [comment]
Segue imagem para melhor representar e compor a US

![MicrosoftTeams-image (1).png](https://images.zenhubusercontent.com/6239dbfdd8cc266a1b2acd2e/c5b4cc20-55d7-4ce7-af31-55052cb09166)
