### ISSUE TITLE
[Encaminhamento] Possibilidade de enviar email 

### ISSUE THREAD

**Issue by lucasferreiraunicef** [UNICEF01/BAV#431]

**Comment by lukasfigueiredo** [comment]
*Corrigir botão "Encerrar" e "Encaminhar" no compoenente Header
*Já envia e-mail, analisar possibilidade de enviar SMS.

**Comment by lucasferreiraunicef** [comment]
@danielbarboni Gentileza verificar as possibilidades de contratação de API externa para SMS ou alguma ja homologada pelo time de ICT. Dito isso, devemos continuar a utilizar a estrutura atual para envio de EMAIL.
