### ISSUE TITLE
FRONT - remover exploid errors

### ISSUE THREAD

**Issue by lukasfigueiredo** [UNICEF01/BAV#435]
Remover erros na tela e deixar apenas no console em ambiente de homologação e produção

**Comment by lucasferreiraunicef** [comment]
Critérios de aceite:

 

- [x] Conter a jornada de usuário completa.

 

- [x] Todas as validações de campo devem estar funcionando.

 

- [x] Deve Conter todos os componentes de tela desenvolvidos com base no protótipo da sprint atual.

 

- [x] Deve ser aceito e aprovado em homologação.
