### ISSUE TITLE
Atualizar Vacinas

### ISSUE THREAD

**Issue by lucasferreiraunicef** [UNICEF01/BAV#445]

**Comment by lucasferreiraunicef** [comment]
@dlazaroni Verificar a alteração a ser realizada. Favor responder nessa thread.

**Comment by dlazaroni** [comment]
Segue a planilha com as alterações:

[https://app.zenhub.com/files/470780401/664287c1-96db-4428-bf0d-43567cbe5d7d/download](https://app.zenhub.com/files/470780401/664287c1-96db-4428-bf0d-43567cbe5d7d/download)

@lukasfigueiredo , @rodrigoluzlopes analisar se os ajustes cabem na sprint. Se couber, repontuar a issue e adicioná-la à sprint.

**Comment by lucasferreiraunicef** [comment]
Pendente análise e filtro a ser realizado pela Tatiane Galleguilos

**Comment by dlazaroni** [comment]
@lucasferreiraunicef , acredito que a Tati já analisou a planilha aqui: https://teams.microsoft.com/l/message/19:84eab1c4722747a7b3fe614519fd84b1@thread.v2/1691686786375?context=%7B%22contextType%22%3A%22chat%22%7D - tem algumas poucas marcações em amarelo dela

**Comment by lucasferreiraunicef** [comment]
Critérios de aceite:

 

- [x] Conter a jornada de usuário completa.

 

- [x] Todas as validações de campo devem estar funcionando.

 

- [x] Deve Conter todos os componentes de tela desenvolvidos com base no protótipo da sprint atual.

 

- [x] Deve ser aceito e aprovado em homologação.
