### ISSUE TITLE
Liberação de menu por perfil - configurações

### ISSUE THREAD

**Issue by rodrigoluzlopes** [UNICEF01/BAV#478]

**Comment by lukasfigueiredo** [comment]
[X] Identificar rota

**Comment by dlazaroni** [comment]
Homologação:

- [ ]  Somente Gestor Nacional visualiza Configurações»MENU/MUNICIPIO e Configurações»MENU/PERFIL

- [ ]  Item de menu "Ferramentas" » remover

- [ ]  Gestor político deve ver o item "Casos" no menu

- [ ]  O item "Painel" do menu aparece para todos os perfis
