### ISSUE TITLE
E-mail - Alerta -> Alteração de Texto

### ISSUE THREAD

**Issue by lucasferreiraunicef** [UNICEF01/BAV#548]
**Texto Definido**

**DE :** Olá, seu filho Tatiane Muniz, a Busca Ativa Vacinal do município Duartina veio te lembrar que seu(ua) filho(a) está com as seguintes vacinas em atrasos:

**PARA:** Olá NOME_DO_RESPONSAVEL,
 
A Busca Ativa Vacinal do município Duartina veio te lembrar que o/a NOME_DA_CRIANCA está com as seguintes vacinas em atrasos:

**Comment by rodrigoluzlopes** [comment]
faltou falar pra mudar o assunto do email disparado:

DE: BAV |  Seu filho(a) está com vacinas em atraso!
PARA: BAV |  Nome_da_crianca está com vacinas em atraso!

Além disso, deixar em negrito a variável Nome_da_crianca no corpo do email:

DE: Olá, Mamãe Teste, A Busca Ativa Vacinal do município Duartina veio te lembrar que o/a Nome da Criançaaa está com as seguintes vacinas em atrasos:

PARA: Olá, Mamãe Teste, A Busca Ativa Vacinal do município Duartina veio te lembrar que o/a Nome da Criançaaa está com as seguintes vacinas em atrasos:

**Comment by lucasferreiraunicef** [comment]
<img width="876" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK1RhQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e912252ae2954efedd4c979b839e823ed88069d1/Captura%20de%20Tela%202024-03-13%20a%CC%80s%2015.41.46.png" alt="Captura de Tela 2024-03-13 às 15.41.46.png" />
