### ISSUE TITLE
Edição de usuário - Campos "Territórios"

### ISSUE THREAD

**Issue by dlazaroni** [UNICEF01/BAV#552]
<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeVpqQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9c2d3ba9ba227639d4a33bb7be8cc20725aa9d8d/image.png" alt="image.png" />

Os campos de "Territórios" na página de edição do usuário estão bloqueados.
O correto é estarem habilitados para selecionar Região / Sub-Região e/ou Sala de Vacina

HABILITAR PARA GESTOR POLÍTICO e COORDENADOR OPERACIONAL

- [ ] Regras de negócio
- [x] Componentes iguais ao protótipo
- [ ] Homologacão de Negócio

**Comment by lucasferreiraunicef** [comment]
Evidência:
[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMlo1QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9e63ab3ab838094b37a065cc4930c0571f65fbee/Gravac%CC%A7a%CC%83o%20de%20Tela%202024-04-19%20a%CC%80s%2011.57.56.mov)

**Comment by lucasferreiraunicef** [comment]
Conforme evidência relatada no vídeo, criei uma ISSUE para correcão dos seguintes itens:

Correcão dos campos abaixo com a message em português

Link da atividade gerada: https://app.zenhub.com/workspaces/bav-62326fc34f75d60017b1263d/issues/gh/unicef01/bav/615


<img width="334" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMmg1QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--fc04009e4d12eb8ce93c13bf1e45a8f45e52fac5/Captura%20de%20Tela%202024-04-19%20a%CC%80s%2012.03.59.png" alt="Captura de Tela 2024-04-19 às 12.03.59.png" />

**Comment by dlazaroni** [comment]
@rodrigoluzlopes @lucasferreiraunicef  Os campos de "Territórios" (Região, Sub Região e Sala de Vacina) não está trazendo os resultados apenas do município relacionado ao usuário. Nesses campos, deve-se trazer somente as regiões, sub-regiões e salas de vacinas do município em questão.

Ver prints do erro:
<img width="1321" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeDU2QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a4b226299c17a00cd799cb2118876f1530ed3673/image.png" alt="image.png" />

O front deveria exibir apenas uma região, duas sub-regiões e as salas de vacina do município de Duartina:
<img width="1322" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeUY2QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--38397ac76d6aad8df860e36e544d213f75288b80/image.png" alt="image.png" />

**Comment by lucasferreiraunicef** [comment]
Confirmo que o dado é recuperado do Back. @rodrigoluzlopes 
<img width="832" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBemQ2QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--19ed829750f738ac2d42b0339601b33156f876e0/Captura%20de%20Tela%202024-04-19%20a%CC%80s%2014.50.18.png" alt="Captura de Tela 2024-04-19 às 14.50.18.png" />

**Comment by dlazaroni** [comment]
@rodrigoluzlopes ainda com problema:
<img width="1212" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMUovQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--07b446cafef8768d3a7ec29950ef6f629b71e02a/image.png" alt="image.png" />

Em Duartina tem somente duas sub-regiões:
<img width="1509" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMVYvQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5270e9e278c04eb69f0321ef2864be059ccfd2fe/image.png" alt="image.png" />

**Comment by dlazaroni** [comment]
@rodrigoluzlopes verificar esses campos na edição do usuário. Para criação do usuário está ok

**Comment by lucasferreiraunicef** [comment]
**Análise:** ISSUE não aprovada a nível de negócio.
**Motivo:** O update não é realizado.

@rodrigoluzlopes 

[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOExGQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--301d02edc8b7f5a9f8d5265d1a7a3b2510698aaa/Gravac%CC%A7a%CC%83o%20de%20Tela%202024-05-08%20a%CC%80s%2014.58.06.mov)

**Comment by lucasferreiraunicef** [comment]
Análise: ISSUE não aprovada a nível de negócio.
Motivo: O update não é realizado para usuarios que ja estejam vinculados a alguma sala de vacina.

@rodrigoluzlopes .

[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeDdvQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d2d5300cb4da597db64b9239ce69af042f157a32/Gravac%CC%A7a%CC%83o%20de%20Tela%202024-05-16%20a%CC%80s%2009.10.57.mov)
