### ISSUE TITLE
Indicadores

### ISSUE THREAD

**Issue by lucasferreiraunicef** [UNICEF01/BAV#562]
[BAV - Indicadores e Métricas.xlsx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdzIzQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d8a6370753f7d1a4afdeac87f58a5813b1c381bb/BAV%20-%20Indicadores%20e%20Me%CC%81tricas.xlsx)

Analisar de 1 ao 18.

**Comment by lukasfigueiredo** [comment]
[relatorio_indicadores_concatenados.xlsx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeFBuQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5c9d9011ec9d2042f51a34396a425d086b621a32/relatorio_indicadores_concatenados.xlsx)

* base de dados usada 16/01/2023
