### ISSUE TITLE
Relatório - Indicadores

### ISSUE THREAD

**Issue by lukasfigueiredo** [UNICEF01/BAV#563]
Description: Utilizar a planilha encaminhada via e-mail como referencia. Sendo que a mesma não está suportando upload no card

**Comment by lukasfigueiredo** [comment]
[relatorio_indicadores_concatenados.xlsx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMXJhQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--fdd59cdbe5aba97c20ac69572ecc0dd9d37dee4e/relatorio_indicadores_concatenados.xlsx)
[relatorio_indicadores-1.xlsx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMXZhQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--32f31b218c8613e740683ee3752614681a6499b0/relatorio_indicadores-1.xlsx)

**Comment by dlazaroni** [comment]
- [ ] Falta incluir coluna "num_usuarios_perfil_Agente_de_Alerta" (após a coluna "cidade")
