### ISSUE TITLE
Bug upload IMAGE

### ISSUE THREAD

**Issue by lucasferreiraunicef** [UNICEF01/BAV#564]
Analisar erro ao enviar imagem no alerta durante a jornada.

**Bug:** Ao inserir a imagem durante o alerta o sistema faz redirect para outra tela e não conclui o upload.

**Comment by dlazaroni** [comment]
@lukasfigueiredo caso precise de mensagem para tratar intermitência: "Serviço temporariamente indisponível. Por favor, aguarde alguns minutos e tente novamente."
