### ISSUE TITLE
Nao permitir criar alerta sem imagem da carteirinha

### ISSUE THREAD

**Issue by lucasferreiraunicef** [UNICEF01/BAV#566]
**Description:** Nao permitir criar alerta sem imagem da carteirinha (Mobile). Verificar se o bug persiste no Desktop.

Ajustar texto: "Envie ao menos uma foto da carteirinha de vacinação"

**Comment by dlazaroni** [comment]
@lukasfigueiredo ajustar texto da descrição da issue
