### ISSUE TITLE
Territórios: Adicionar novas salas de vacina do CNES

### ISSUE THREAD

**Issue by dlazaroni** [UNICEF01/BAV#569]
1) importação geral atualizada da base do CNES - ftp://ftp.datasus.gov.br/cnes/BASE_DE_DADOS_CNES_202401.ZIP (extraído daqui: https://cnes.datasus.gov.br/pages/downloads/arquivosBaseDados.jsp)
- 
- Utilizar todos os estabelecimentos disponíveis em no CSV **tbEstabelecimento** no banco importando os dados das colunas CO_CNES, CO_MUNICIPIO, CO_ESTADO, NO_FANTASIA, LOGRADOURO, BAIRRO, NU_LATITUDE, NU_LONGITUDE

2) modal de pesquisa de outras salas de vacinas da base bruta do CNES para adicionar 

Definição de Preparado
- [x] Description
- [x] Regra
- [ ] Exemplo/Protótipo

**Comment by lucasferreiraunicef** [comment]
@dlazaroni verificar se o CNES a ser inserido pertence a categoria inserida no painel.
