### ISSUE TITLE
Usuário não pode estar em duas UBS diferentes

### ISSUE THREAD

**Issue by rodrigoluzlopes** [UNICEF01/BAV#577]
Critérios de Aceite:

- [x] Homologação de negócio
- [x] Componentes equivalentes ao Protótipo

**Comment by dlazaroni** [comment]
@lucasferreiraunicef já validei, mas criei uma nova issue de evolução dessa entrega que podemos priorizá-la em outro momento: https://app.zenhub.com/workspaces/bav-62326fc34f75d60017b1263d/issues/gh/unicef01/bav/579

**Comment by lucasferreiraunicef** [comment]
@dlazaroni perfeito, devemos iniciar nosso deploy. @rodrigoluzlopes
