### ISSUE TITLE
Relatório Adesão

### ISSUE THREAD

**Issue by dlazaroni** [UNICEF01/BAV#578]
Na página de Adesões, devemos ter um botão EXPORTAR que exporta um xlsx com as seguintes colunas:

1) Município
2) Estado
3) Status da adesão
4) Pendências
5) E-mail prefeito
6) E-mail gestor da política municipal

Para um melhor desempenho analisar se esse export é atualizado diariamente ou no momento da exportação.

Critérios de Aceite:

- [ ] Homologação de negócio
- [x] Componentes equivalentes ao Protótipo 
- [x] Regra de negócio

**Comment by lucasferreiraunicef** [comment]
@rodrigoluzlopes de acordo com a imagem, está faltando 2 itens de coluna: 

E-mail prefeito
E-mail gestor da política municipal

<img width="720" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBek1QQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6c18bd7d37425b1a46235a76459096f0c9d7f487/Captura%20de%20Tela%202024-03-26%20a%CC%80s%2012.07.11.png" alt="Captura de Tela 2024-03-26 às 12.07.11.png" />

**Comment by dlazaroni** [comment]
1) tarefa sem deploy @lucasferreiraunicef 
2) verificar possibilidade de "Todos" nos dois componentes de filtros
