### ISSUE TITLE
[Territórios] Remover usuário da listagem de usuários caso ele já esteja relacionado em algum nível de território

### ISSUE THREAD

**Issue by dlazaroni** [UNICEF01/BAV#579]
Critérios de Aceite:

- [ ] Homologação de negócio
- [x] Componentes equivalentes ao Protótipo

**Comment by lucasferreiraunicef** [comment]
Segue evidência:

A issue não atingiu o objetivo de cenário esperado conforme Regra de Negócio levantada pelo P.O. @rodrigoluzlopes 

[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeEdaQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--74f5aaa6a9b3649c0092e14e9d0f02c85fad8106/Gravac%CC%A7a%CC%83o%20de%20Tela%202024-04-26%20a%CC%80s%2012.28.57.mov)

**Comment by lucasferreiraunicef** [comment]
Análise: ISSUE não aprovada a nível de negócio.
Motivo: Usuário não é excluido.  A mensagem de erro diz que está faltando ID

[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBelBvQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b863f294d83e1eea90ad1e8c31dbb6f6bfbc4479/Gravac%CC%A7a%CC%83o%20de%20Tela%202024-05-16%20a%CC%80s%2009.29.45.mov)

**Comment by lucasferreiraunicef** [comment]
Fazer video
