### ISSUE TITLE
[Alerta] Exclusão de um alerta emitido

### ISSUE THREAD

**Issue by dlazaroni** [UNICEF01/BAV#580]
Na listagem de alertas, a plataforma está dando erro ao tentar excluir/deltar um alerta emitido

Definição de Preparado
- [x] Description
- [x] Regra
- [x] Exemplo/Protótipo

**Comment by dlazaroni** [comment]
@lucasferreiraunicef  @rodrigoluzlopes issue aprovada com a ressalva de que ela gerou uma nova demanda: https://app.zenhub.com/workspaces/bav-62326fc34f75d60017b1263d/issues/gh/unicef01/bav/612

**Comment by lucasferreiraunicef** [comment]
Para complementar, segue evidência:

[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNGR6QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--097423eebf1466c9d05322737dbf13a2a559427d/Gravac%CC%A7a%CC%83o%20de%20Tela%202024-04-18%20a%CC%80s%2013.10.12.mov)
