### ISSUE TITLE
Melhoria validação Alerta

### ISSUE THREAD

**Issue by lukasfigueiredo** [UNICEF01/BAV#583]
Traduz nomes de campos para português nas mensagens de validação de entrada.
Por exemplo: 
 - mother_name => nome da mãe
 - father_email => email do pai
 - etc

**Comment by lucasferreiraunicef** [comment]
@dlazaroni

**Comment by dlazaroni** [comment]
@lucasferreiraunicef não achei o name do campo CELULAR da mãe e do pai, você achou?

**Comment by lucasferreiraunicef** [comment]
<img width="1047" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK1BhQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--33a24ae15930c7a07d97a11210f7eb32aac130d1/Captura%20de%20Tela%202024-03-13%20a%CC%80s%2015.40.42.png" alt="Captura de Tela 2024-03-13 às 15.40.42.png" />

Confere ?
