### ISSUE TITLE
Edição de Usuário: não permitir troca de município

### ISSUE THREAD

**Issue by dlazaroni** [UNICEF01/BAV#588]
Definição de Preparado
- [x] Description
- [x] Regra
- [ ] Exemplo/Protótipo

- [x] Regras de negócio
- [x] Componentes iguais ao protótipo
- [x] Homologacão de Negócio

**Comment by lucasferreiraunicef** [comment]
Evidência:

[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNFo1QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a6ce34c90c4ed7820859316638880fee09961d3b/Gravac%CC%A7a%CC%83o%20de%20Tela%202024-04-19%20a%CC%80s%2012.17.49.mov)
