### ISSUE TITLE
Interface Web Modal Pesquisa Inserir Sala de vacina

### ISSUE THREAD

**Issue by lukasfigueiredo** [UNICEF01/BAV#604]
<img width="1329" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBemE0QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--40f42f238299432e601bb45a5656d599fa826ce3/image.png" alt="image.png" />

Na listagem do select:

Código CNES - Nome do Estabelecimento 

"13245235 - Hospital Santa Maria"

Botão "Adicionar" aparece após selecionar um estabelecimento no select

**Comment by lucasferreiraunicef** [comment]
@dlazaroni
