### ISSUE TITLE
Definição gerenciador de tarefas CRON ou Jenkins

### ISSUE THREAD

**Issue by lukasfigueiredo** [UNICEF01/BAV#609]

**Comment by rodrigoluzlopes** [comment]
Através do estudo realizado por ambas as partes, usaremos o JOBS do Laravel.

**Comment by rodrigoluzlopes** [comment]
https://laravel.com/docs/11.x/scheduling
https://laravel.com/docs/11.x/scheduling#scheduling-artisan-commands
