### ISSUE TITLE
[BUG] Correcão de verificacao de CPF (Criacão do Alerta)

### ISSUE THREAD

**Issue by lucasferreiraunicef** [UNICEF01/BAV#612]
**Description:** Após o ALERTA ser excluído para um CPF, ao tentar criar novamente, a aplicacão executa o seguinte o comportamento.

<img width="1560" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeUJsQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c946c134580d6a9052364595147f4f61ad072a93/imagem.png" alt="imagem.png" />

**Comment by lucasferreiraunicef** [comment]
Reanálise do Cenário apresentado pelo P.O @dlazaroni :


[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNXh6QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--00bb9ec5accbd784cd124188bd46062535728d50/Gravac%CC%A7a%CC%83o%20de%20Tela%202024-04-18%20a%CC%80s%2013.17.09.mov)


@dlazaroni gentileza homologar.

**Comment by dlazaroni** [comment]
@lucasferreiraunicef  @lukasfigueiredo perfeito
