### ISSUE TITLE
Relatório adesão - expor full em produção

### ISSUE THREAD

**Issue by dlazaroni** [UNICEF01/BAV#620]
Referente à task realizada - https://app.zenhub.com/workspaces/bav-62326fc34f75d60017b1263d/issues/gh/unicef01/bav/578 - 

Em produção, não estou conseguindo exportar o relatório full (com os dois componentes da listagem de adesão no "Todos").

**Comment by rodrigoluzlopes** [comment]
Adicionar exclusão lógica na tabela de logs

**Comment by lucasferreiraunicef** [comment]
- [x] Atingiu o objetivo esperado

[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNDcyQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e06b56b6bf6c4d1b727db948fb481f273f6981f2/Gravac%CC%A7a%CC%83o%20de%20Tela%202024-05-20%20a%CC%80s%2013.41.45.mov)
