### ISSUE TITLE
[Alertas] Listagem - Alertas pendentes

### ISSUE THREAD

**Issue by dlazaroni** [UNICEF01/BAV#621]
https://testes.buscaativavacinal.org.br/records/list?status=pending

Essa listagem não deve listar registros com a etapa atual "Concluído".

Etapa: Alerta
Status: Aguardando Análise Técnica

**Comment by rodrigoluzlopes** [comment]
<img width="1591" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNUpoQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--91c7fe8efd44e739d36c7f2bd0cc854bd53d1808/image.png" alt="image.png" />
