### ISSUE TITLE
Adicionar usuário Região/SubRegião

### ISSUE THREAD

**Issue by lukasfigueiredo** [UNICEF01/BAV#625]

**Comment by rodrigoluzlopes** [comment]
<img width="1600" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeVRWQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--baa56f62bef66ba7cbfbb6e262b30d03b3071ae4/WhatsApp%20Image%202024-05-10%20at%2014.03.26.jpeg" alt="WhatsApp Image 2024-05-10 at 14.03.26.jpeg" />

**Comment by lucasferreiraunicef** [comment]
- [x] Atingiu o Objetivo esperado

Obs: Necessário verificar a perfomance

[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL0huQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c5fe814ed4e3636ce23c3cc9fcf17389930d486f/Gravac%CC%A7a%CC%83o%20de%20Tela%202024-05-16%20a%CC%80s%2008.47.49.mov)
