### ISSUE TITLE
Listagem completa sala de vacina

### ISSUE THREAD

**Issue by lukasfigueiredo** [UNICEF01/BAV#627]
A listagem de sala de vacina no formulário de alerta/visita não está exibindo todas as salas de vacina

**Comment by lucasferreiraunicef** [comment]
- [x] Atingiu o objetivo esperado

[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeS9vQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e305dd1dc55f828c8cc057ad370c19f5735171c6/Gravac%CC%A7a%CC%83o%20de%20Tela%202024-05-16%20a%CC%80s%2009.22.08.mov)
