### ISSUE TITLE
Exibir versão ultimo release no Front

### ISSUE THREAD

**Issue by lukasfigueiredo** [UNICEF01/BAV#628]

**Comment by dlazaroni** [comment]
- [ ] Tirar da tela de login e deixar somente no rodapé das telas logadas
- [ ] Diminuir a font para 10px

<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeTBkQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2719f23bd1b784005d45209cd522549292ac534e/image.png" alt="image.png" />
