### ISSUE TITLE
Error de URL RESET DE SENHA

### ISSUE THREAD

**Issue by lucasferreiraunicef** [UNICEF01/BAV#629]
Description: Ao resetar senha, a aplicacão utiliza como BASE a URL de producão, sendo o que o esperado é que utilize a URL do proprio ambiente.

**Comment by rodrigoluzlopes** [comment]
alterar as variaǘeis de ambiente em teste e produção

Testes
URL_EMAIL_SERVICE=https://testes.buscaativavacinal.org.br
APP_URL=https://testes.buscaativavacinal.org.br

Produção
URL_EMAIL_SERVICE=https://buscaativavacinal.org.br
APP_URL=https://buscaativavacinal.org.br
