### ISSUE TITLE
Erro ao Logar

### ISSUE THREAD

**Issue by lucasferreiraunicef** [UNICEF01/BAV#631]
**Descrição do Bug** 

**Versão:** 1.1.0 

**Ambiente:** Produção

**Passos para reprodução:** https://buscaativavacinal.org.br/login

**Resultado esperado:** Login realizado com sucesso

**Resultado encontrado:** Aparece a msg de " As credenciais não foram encontradas em nossos registros " 

**Evidência:** 

<img width="1417" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMXNDQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d8295b96475a49958557521eb069f1b461cebcff/Captura%20de%20Tela%202024-05-22%20a%CC%80s%2013.16.52.png" alt="Captura de Tela 2024-05-22 às 13.16.52.png" />

**Comment by lucasferreiraunicef** [comment]
[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM0FIQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--24baba8c2be80180e13c9497e8cf4c3981642e7d/Gravac%CC%A7a%CC%83o%20de%20Tela%202024-05-23%20a%CC%80s%2010.00.38.mov)

**Comment by dlazaroni** [comment]
a senha estava incorreta
