### ISSUE TITLE
Relatório Adesão

### ISSUE THREAD

**Issue by dlazaroni** [UNICEF01/BAV#632]
O email com o relatório da adesão para o status "Todos" e estado "Todos" não chega por email

Versão: 1.1.0

Ambiente: Produção

Passos para reprodução: https://buscaativavacinal.org.br/accession

Resultado esperado: Email com o xls da adesão para todos os status de todos os estados

Resultado encontrado: Aparece mensagem de sucesso mas email não chega

Evidência:
<img width="1780" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNk1DQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--da61b890d2283369e92c9ed7ffc0c3ba85138818/image.png" alt="image.png" />

**Comment by rodrigoluzlopes** [comment]
@dlazaroni , a resolução foi enviada ontem para produção.
